name: 배포

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    # https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

    steps:
      - name: 환경변수 주입
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          echo

      - name: 체크아웃
        uses: actions/checkout@v3

      - name: client 모듈 설치
        working-directory: ./client
        run: npm install

      - name: client 빌드
        working-directory: ./client
        run: |
          npm run build
          rm -rf /var/www/build
          cp -rf ./build /var/www/

      - name: server 모듈 설치
        working-directory: ./server
        run: npm install

      - name: server 환경변수 파일 생성
        working-directory: ./server
        run: |
          echo DATABASE_URL=${{ env.DATABASE_URL }} > .env
          echo REDIS_HOST=${{ env.REDIS_HOST }} >> .env
          echo REDIS_PORT=${{ env.REDIS_PORT }} >> .env
          echo REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} >> .env

      - name: 배포
        working-directory: ./server
        run: |
          echo 배포 시작
