name: 배포

on:
  push:
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

jobs:
  deploy:
    runs-on:
      self-hosted
      # https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: client 빌드
        working-directory: ./client
        run: |
          npm run build
          rm -rf /var/www/build
          cp -rf ./build /var/www/

      - name: server 모듈 설치
        working-directory: ./server
        run: npm install

      - name: server 환경변수 파일 생성
        working-directory: ./server
        run: |
          echo DATABASE_URL=$DATABASE_URL > .env
          echo REDIS_HOST=$REDIS_HOST >> .env
          echo REDIS_PORT=$REDIS_PORT >> .env
          echo REDIS_PASSWORD=$REDIS_PASSWORD >> .env

      - name: pm2 프로세스 재실행
        working-directory: ./server
        run: pm2 restart japari
